version: '3.7'

services:

  mongodb:
    image: mongo
    container_name: TGDataset
    restart: always
    networks:
      - app-tier
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: Telegram_test


  python_app:
    build: .
    depends_on:
      - mongodb
    networks:
      - app-tier
    ports:
      - "8000:8000"
    environment:
      MONGO_INITDB_DATABASE: Telegram_test
      MONGO_DB_URL : 'mongodb://TGDataset'
    #volumes:
    #  - /public_db:/app/public_db



  build_db:
      build:
        context: ./
        dockerfile: python_create_db.Dockerfile
      depends_on:
        - mongodb
      networks:
        - app-tier
      ports:
        - "8000:8000"
      environment:
        MONGO_INITDB_DATABASE: Telegram_test
        MONGO_DB_URL : 'mongodb://TGDataset'
      volumes:
        - ./public_db:/app/public_db



networks:
  app-tier:
    driver: bridge